# Cloudflare Pages Configuration for SteakNStake Frontend

name = "steaknstake"
compatibility_date = "2024-10-24"
pages_build_output_dir = "out"

[env.production]
name = "steaknstake-production"

[env.preview] 
name = "steaknstake-preview"