# Cloudflare Pages Configuration for SteakNStake Frontend
# Updated for deployment fix

name = "steaknstake"
compatibility_date = "2025-10-28"
pages_build_output_dir = "out"

[env.production]
name = "steaknstake-production"

[env.preview] 
name = "steaknstake-preview"